### PR TITLE
Fix exporting `LinkParams` and `UILinkParams` types

### LINKED ISSUE #717: Unfound exports `LinkParams` and `UILinkParams` under Embroider
I assume this is because these exports are actually TS interfaces and should be exported using `export type`?

```
WARNING in ./node_modules/ember-link/index.js 1:0-75
export 'LinkParams' (reexported as 'LinkParams') was not found in './link' (possible exports: UILink, default, isQueryParams)
 @ ./components/dropdown/actions/link/index.js 13:0-34 16:117-121
 @ ./tests/integration/components/dropdown/actions/link-test.js 5:0-74 7:9-11
 @ ./assets/test.js 32:13-85

WARNING in ./node_modules/ember-link/index.js 1:0-75
export 'UILinkParams' (reexported as 'UILinkParams') was not found in './link' (possible exports: UILink, default, isQueryParams)
 @ ./components/dropdown/actions/link/index.js 13:0-34 16:117-121
 @ ./tests/integration/components/dropdown/actions/link-test.js 5:0-74 7:9-11
 @ ./assets/test.js 32:13-85
```

### PR DESCRIPTION
**Pull request by bertdeblock**
Closes #717.

### CODE REVIEW

**Comment by bertdeblock** [comment]
@buschtoens Would you mind checking if this change is correct?

**Review by buschtoens — APPROVED** [review]
Perfect, thank you!

Sorry, that this PR has slipped my attention.

**Comment by bertdeblock** [comment]
@buschtoens No problem! If you have some time, would you mind cutting a release with this fix?

**Comment by Turbo87** [comment]
@bertdeblock https://github.com/buschtoens/ember-link/releases/tag/v2.0.1 :)

**Comment by bertdeblock** [comment]
Awesome, thank you @Turbo87!

**Pull request merged**
